spring:
  application:
    name: cloud-coupon
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  cache:
    type: redis
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
server:
  port: 8081